PROPOSAL.md
This is the project proposal, following the template provided in UMLearn.
=> Initial Project Proposal

documentation/meeting-logs/2023-09-18.md, documentation/meeting-logs/2023-09-25.md
added meeting duration for both meeting logs
=> meeting durations added

documentation/meeting-logs/2023-10-02.md
=> 2023-10-02 meeting notes

README.md
- Add a description of the repo
- Add architecture image
- Update documentation links, since old ones didn't work because we didn't update them when we changed the file structure
=> Updated documentation links and added architecture diagram

server/prisma/schema.prisma, server/src/test/unit/routes/auth.test.ts
Created models for User, Expense, GroupExpense,GroupExpenseSplit, and Budget.
Closes #38 
Closes #24 
Closes #29
=> Created DB schema in Prisma

documentation/test-plan.md, server/src/app.ts, server/src/config/config.ts, server/src/routes/auth.ts, server/src/routes/expenses.ts, server/src/test/unit/routes/auth.test.ts, server/src/test/unit/routes/expenses.test.ts, server/src/types/types.d.ts
- `GET /users/:userId/expsenses` retrieves all expenses (individual only for now) for a user
- `POST /expenses` creates a new expense for the user, based on the userId decoded from the authentication token
- `PUT /expenses/:expenseId` updates an expense
- `DELETE /expenses/:expenseId` deletes an expense
- `GET /expenses/:expenseId` retrieves an invidiual expense
Closes #52 
Test coverage:
```
C:\Users\Danie\workspace\Spendr\server> npx jest --collect-coverage --verbose
PASS  src/test/unit/middleware/authenticate.test.ts
authenticate middleware
√ responds with 401 if no token is provided (11 ms)
√ responds with 401 if an invalid token is provided (1 ms)
√ responds with 401 if the decoded token is a string (1 ms)
√ calls next function if a valid token is provided
√ decodes the userId from a …
```
=> Expenses API routes

server/src/app.ts, server/src/middleware/errorHandling.ts, server/src/routes/auth.ts, server/src/routes/expenses.ts
Errors are logged for user and system issues that occur within the server. The logs are found under server/logs separated by user and sys errors.
=> Created error logging

.github/workflows/ci.yml
Lint and build server and client, and test server with Jest. 
Will change `branches:` to `main` right before merge.
Note: 
- Server tests will fail until we set the `secrets.JWT` GitHub secret.
- Client linting passes with warnings, but has expected formatting errors that need to be fixed in another PR
- Server linting and formatting passes
Closes #12
=> GitHub Actions CI workflow with lint, build, test

client/src/components/Header/Header.tsx
When a user clicks the logout button, the userId and token context are nullified and the user is redirected to the landing page `/`.
=> Logout Integration

client/src/App.tsx, client/src/components/Header/Header.tsx, client/src/context/UserContext.tsx, client/src/interfaces/interfaces.ts, client/src/pages/Expenses/Expenses.tsx, client/src/pages/Home/Home.tsx, client/src/pages/UserSettings/UserSettings.tsx
- user is now redirected to greetings page if they try to access an insider page without being logged in
- removed `isLoggedIn` prop from header as the header is used only when logged in
=> UI cleanup

documentation/meeting-logs/2023-09-18.md, documentation/meeting-logs/2023-09-25.md, documentation/meeting-logs/2023-10-02.md, documentation/meeting-logs/2023-10-09.md
We really didn't talk about specific issues until the meeting before last. The changes to the most recent meeting is in https://github.com/BarbzCodez/Spendr/pull/76
=> added reference to github issues

client/src/pages/Expenses/Components/ExpenseTable.tsx
expense table was not sorting the amount as we added $ at the front. removed it and it works again
=> ExpenseTable amount sorting fixed

documentation/project-proposal.md
- Updated user stories to better reflect what we are gonna work on
=> Update User Stories

documentation/development.md
Added developer documentation. I felt like a lot of information about dev was spread throughout our Discord so I decided to try to put it all in one place for quicker reference.
Closes #92
=> Added developer documentation

server/prisma/schema.prisma, server/src/app.ts, server/src/routes/budgets.ts, server/src/test/unit/routes/budgets.test.ts
- Created `POST /budgets` to allow users to create budgets with an `amount`, `category`, `duration`.
- `category` is **optional**, and must be one of the defined categories in prisma
- `duration` must be one of the defined durations in prisma ('WEEKLY', 'MONTHLY', 'YEARLY')
- Unit tests
- Modified and re-formatted prisma model
Code coverage report:
```
------------------|---------|----------|---------|---------|-------------------
File              | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
------------------|---------|----------|---------|---------|-------------------
All files         |     100 |      100 |     100 |     100 |
src              |     100 |      100 |     100 |     100 |
app.ts          |     100 |      100 |     100 |     100 |
src/middleware   | …
```
=> Create budget api

client/src/assets/styles/theme.ts, client/src/components/ExpenseDialog/ExpenseDialog.tsx, client/src/components/Header/Header.tsx, client/src/pages/Expenses/Components/ExpenseTable.tsx, client/src/pages/Expenses/Components/styles.ts, client/src/pages/Login/components/LoginForm.tsx, client/src/pages/Signup/components/SignupForm.tsx, client/src/pages/UserSettings/components/SettingsListItem.tsx, client/src/pages/UserSettings/components/styles.ts, client/src/pages/UserSettings/styles.ts
- colors in data grid and expense dialog were not consistent
- fix: add dark mode to global theme so that foreground colors automatically become white
closes #95
=> Colors fixed

server/src/routes/auth.ts, server/src/test/unit/routes/auth.test.ts, server/src/types/budgetTypes.d.ts, server/src/types/expenseTypes.d.ts, server/src/utils/expenses.ts
- `GET /users/:userId/budgets` 
- Returns a list of the users budgets, and the `totalExpense`- the total expenses that have gone towards the budget so far
- Resets on first day of week, month, and year
Closes #107
=> Fetch users budgets API

documentation/development.md, documentation/meeting-logs/2023-09-18.md, documentation/meeting-logs/2023-09-25.md, documentation/meeting-logs/2023-10-02.md, documentation/meeting-logs/2023-10-09.md, documentation/meeting-logs/2023-10-16.md
I was looking at the dev docs and I got a bunch of squiggly lines from markdown lint, so I cleaned them up and the logs too
No content change, just making the linter happy :)
=> Markdown lint docs

documentation/meeting-logs/2023-10-23.md
=> 2023 10 23.md

server/src/routes/budgets.ts, server/src/test/unit/routes/budgets.test.ts
PR for the api put request for budgets, which allows for existing budgets to be updated.
=> budget put api and tests

server/src/routes/budgets.ts, server/src/test/unit/routes/budgets.test.ts
The tests and api for deleting a budget
=> budgets delete api endpoint

documentation/meeting-logs/2023-10-23.md
Correcting Barb's and Victoria's notes for 10-23
=> 2023-10-23 revert

client/package-lock.json, client/package.json, client/src/api/EdenAPI.ts, client/src/assets/styles/styles.ts, client/src/assets/styles/theme.ts, client/src/components/ExpenseDialog/ExpenseDialog.tsx, client/src/interfaces/interfaces.ts
Added receipt image parsing, which autofills the add expense form.
**We now need to store an API key in the client for this to work**. More info in Discord
**Each image parsing costs ~$0.01 each**, I have ~$8.00 credit left with my API key.
Closes #129
=> Receipt image parsing and expense form autofill

server/src/routes/users.ts, server/src/test/unit/routes/users.test.ts
Forgot we need to do this when reviewing, but it's ok it's a quick fix
=> Made analytics endpoints return objects with keys

documentation/test-plan.md, server/docker-compose.test.yml, server/jest.config.js, server/package.json, server/run-integration-tests.sh, server/src/test/integration/budgets/createBudget.test.ts, server/src/test/integration/expenses/createExpense.test.ts, server/src/test/integration/expenses/deleteExpense.test.ts, server/src/test/integration/groupExpenses/createGroupExpense.test.ts, server/src/test/integration/groupExpenses/markGroupExpenseAsPaid.test.ts, server/src/test/integration/resetDb.ts, server/src/test/integration/setup.ts, server/src/test/integration/users/deleteUser.test.ts, server/src/test/integration/users/login.test.ts, server/src/test/integration/users/register.test.ts, server/src/test/integration/users/resetPassword.test.ts, server/src/test/integration/users/updateUser.test.ts
- Added 10 integration tests
- Updated description of integration tests in test plan
- Added scripts to run integration tests
- Added `docker-compose.test.yml` that starts up the test database for the integration tests
**Running the integration tests locally**:
```
cd server
npm install 
npm test:integration
```
**Note**: Integration tests must be ran in a shell that has access to linux commands. Git Bash works on Windows.
Closes #109 
test output:
```
Danie@DESKTOP-V0I9QO6 MINGW64 ~/workspace/Spendr/server (integration-tests)
$ npm run test:integration
> server@1.0.0 test:integration
> sh ./run-integration-tests.sh
Network server_default  Creating
Network server_default  Created
Container server-pgadmin-1  Creating
Container server-test-db-1  Creating
Container server-pgadmin-1  Created …
```
=> Integration tests

documentation/meeting-logs/2023-10-16.md, documentation/meeting-logs/2023-10-23.md, documentation/meeting-logs/2023-10-30.md, documentation/meeting-logs/2023-11-13.md
- Added notes for Meeting 9
- Reformatted previous notes so that they are consistent
=> Add Meeting 9 + formatting

client/src/pages/Budgets/Budgets.tsx, client/src/pages/Budgets/styles.ts, client/src/pages/Home/Home.tsx, client/src/pages/Home/styles.ts, client/src/pages/UserSettings/UserSettings.tsx, client/src/pages/UserSettings/styles.ts, client/src/styles.ts
Victoria found a weird display on the home page when the display is bigger
I also refactored a div that I resued :)
=> fix ui not displaying properly in bigger screens

.github/workflows/sonarcloud.yml
=> Security Analysis with SonarCloud

.github/workflows/sonarcloud.yml, sonar-project.properties
Will update branches to main before merge.
=> SonarCloud SCM environment and version fix

documentation/meeting-logs/2023-11-20.md, documentation/meeting-logs/2023-11-27.md
Added notes for our last meeting + fixed a typo
=> Meeting 11

documentation/development.md
We need to specify the coding standards explicitly in the documentation
=> Added documentation for defining coding standard

client/src/api/BudgetAPI.ts, client/src/api/ExpenseAPI.ts, client/src/api/GroupExpensesAPI.ts, client/src/api/UserAPI.ts
API URL must now be set in `client/.env` as `REACT_APP_API_URL=http://localhost:3000`. This allows us to change the API url in our production server to be the actual server URL, rather than localhost.
=> Dynamic API URLs

.vscode/settings.json, documentation/release-summary.md
- Adjusted sample `docker-compose.yml` to point to the latest image
- Fixed several typos
- Adjust team roles to reflect what's in the test plan
=> Release summary fixes

client/src/api/BudgetAPI.ts, client/src/api/ExpenseAPI.ts, client/src/api/GroupExpensesAPI.ts, client/src/api/UserAPI.ts, documentation/test-plan.md, server/src/app.ts, server/src/test/integration/budgets/createBudget.test.ts, server/src/test/integration/expenses/createExpense.test.ts, server/src/test/integration/expenses/deleteExpense.test.ts, server/src/test/integration/groupExpenses/createGroupExpense.test.ts, server/src/test/integration/groupExpenses/markGroupExpenseAsPaid.test.ts, server/src/test/integration/users/deleteUser.test.ts, server/src/test/integration/users/login.test.ts, server/src/test/integration/users/register.test.ts, server/src/test/integration/users/resetPassword.test.ts, server/src/test/integration/users/updateUser.test.ts, server/src/test/unit/routes/budgets.test.ts, server/src/test/unit/routes/expenses.test.ts, server/src/test/unit/routes/groupExpenses.test.ts, server/src/test/unit/routes/users.test.ts
- Tested manually in the client
- Unit tests pass
- Integration tests pass
=> Added /api prefix to all API endpoints
